#!/bin/bash

for i in {1..2..1}
do
	../blender_tanvi/blender -P scripts/pillared_warehouse/warehouse_pillared_new.py -b
	python3 scripts/GenerateEgoCentricLayouts.py
	mv "./datasets" "./datasets_${i}"
done
python3 scripts/datasetMerge/mergeDatasets.py
date